### ISSUE TITLE
cutscene build bugs

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHMelonMix#186] opened 2024-07-18 07:05 UTC
**Double cutscenes fail**
currently any scene that has back to back cutscenes do not play the second scene , examples being xions death and post riku fight , likely due to pressing skip skipping them both . can be fixed short term by simply merging them together but long term will be a problem playing them in theatre mode when it comes to playing them individually so thats not ideal

**Credits bugged**
the credits cutscene is bugged , it will play the original ds audio sped up with a black screen and never end , this is likely due to how the end screen works . the end screen is considered part of the cutscene , if you skip the credits it skips the end screen which is a problem . does work if played through theatre mode but that in and of itself is bugged

**Inconsistent player**
sometimes scenes wont play correctly , instead it will skip the ds scene without playing the hd scene with one of two scenarios  : either the audio of it will continue playing over the game until it either ends or another scene plays , or the scene will fully skip with not even the hd scenes audio playing . not consistent

**Patched ROMs**
patched roms do not work , the game simply does not play the hd scenes . this goes for patches that do not touch the "mv" folder in the rom as well , meaning audio mods and fan translations are broken

minor bugs (arent game breaking) :
when an hd scene starts or ends it shows a frame from a seemingly random point in the past

when an hd scene starts the in engine music speeds up , a result of the current method used so theres no real way to get around it yet + should be fixed with music replacement (unless its fixed beforehand)

regarding the previous point ^ on occasion after an hd scene plays sometimes music from before the cutscene is heard . again , its just a result of the current method used and will likely be fixed

**Comment by ZLGNF** [comment] 2024-07-23 21:28
As of the [latest build](https://github.com/vitor251093/KHMelonMix/actions/runs/10052097630), in New Game, the DS Opening will play after the HD Opening finishes or is skipped.

If you stay in the title screen for too long the opening will try to play but as for right now, it doesn't play and instead the emulator speeds up and the screen turns black. Keep in mind, you're still in the title screen as you can hear the music faster then normal and you can try to load your saves and if you do manage to load a save the HD opening will play before the game continues as normal.

And then you have the whole "The same cutscene can't be played again unless another cutscene plays"

**Comment by vitor251093** [comment] 2024-07-25 01:53
- If you play an HD replacement cutscene from the Theater, the old cutscene will play right after it; also, two of the cutscene will trigger two cutscenes (workaround)

- Credits are bugged

- The cutscenes from the HD Collection should be loaded if available (fallback if they aren't in the assets folder)

- Input settings window doesn't have the joystick image for some people for some reason

**Comment by vitor251093** [comment] 2024-07-25 23:36
Updated complete list:

Cutscenes that happen one after the other don't work, like Xion's death and post Riku fight: **FIXED**

Credits bugged: 
the credits cutscene is bugged , it will play the original ds audio sped up with a black screen and never end , this is likely due to how the end screen works . the end screen is considered part of the cutscene , if you skip the credits it skips the end screen which is a problem . does work if played through theatre mode but that in and of itself is bugged

Inconsistent player: **MAY BE FIXED; NEEDS CONFIRMATION**

Patched ROMs: **WON'T BE SUPPORTED AT THIS MOMENT**

When an HD scene starts or ends it shows a frame from a seemingly random point in the past: **NOT FIXED YET; COULD NOT REPRODUCE**

When an HD scene starts the in engine music speeds up: **NOT FIXED YET**

On occasion after an HD scene plays sometimes music from before the cutscene is heard: **NOT FIXED YET**

The DS Opening will play after the HD Opening finishes or is skipped: **FIXED**

If you stay in the title screen for too long the Opening will try to play but as for right now, it doesn't play and instead the emulator speeds up and the screen turns black: **MAY BE FIXED; NEEDS CONFIRMATION**

The same cutscene can't be played again unless another cutscene plays: **NOT FIXED YET**

If you play an HD replacement cutscene from the Theater, the old cutscene will play right after it: **MAY BE FIXED; NEEDS CONFIRMATION**

Two of the cutscenes in the Theater will trigger two additional cutscenes: **NOT FIXED YET**

The cutscenes from the HD Collection should be loaded if available (fallback if they aren't in the assets folder): **NOT FIXED YET**

**Comment by vitor251093** [comment] 2024-07-28 14:12
As discovered by Magnus, address 0x0204C21C carries the misdion

**Comment by vitor251093** [comment] 2024-08-08 03:11
All issues fixed, or turned into independent issues

**Closed by vitor251093** 2024-08-08 03:11 UTC
Labels: bug
