### ISSUE TITLE
days general issues , 0.4.2 & 0.4.3

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHMelonMix#243] opened 2024-09-03 12:37 UTC
- game starts in "top window" aspect ratio , distorting the game
- theatre mode and mission mode character select screen colour detection is messed up again taking from the red top left row of pixels rather than the black borders everywhere else
- load menu has some sort of grey or washed out filter placed over it when loading from the main menu , same with the mission mode solo and multiplayer screens . story mode save displays properly
- story mode roxas menu displays single screen , only happens when accessing the menu from the grey area
- this ^ also affects the holo , challenge mission and saix menus , and when withdrawing from a mission in mission mode , making selecting missions impossible . completing a mission in mission mode fixes itself , story mode is still bugged when completing a mission
- loading screens fast forward should be togglable

**Comment by vitor251093** [comment] 2024-09-04 23:28
> - story mode roxas menu displays single screen , only happens when accessing the menu from the grey area
> - this ^ also affects the holo , challenge mission and saix menus , and when withdrawing from a mission in mission mode , making selecting missions impossible . completing a mission in mission mode fixes itself , story mode is still bugged when completing a mission

Fixed on the latest Actions build

**Comment by vitor251093** [comment] 2024-09-04 23:38
> - load menu has some sort of grey or washed out filter placed over it when loading from the main menu , same with the mission mode solo and multiplayer screens . story mode save displays properly

Unable to reproduce

> - theatre mode and mission mode character select screen colour detection is messed up again taking from the red top left row of pixels rather than the black borders everywhere else

Fixed on the latest Actions build

**Comment by vitor251093** [comment] 2024-09-04 23:46
> - game starts in "top window" aspect ratio , distorting the game

Fixed on the latest Actions build

**Comment by vitor251093** [comment] 2024-09-04 23:50
> - loading screens fast forward should be togglable

Will be fixed by #55

**Closed by vitor251093** 2024-09-04 23:50 UTC
Labels: bug
