### ISSUE TITLE
V0.2.2 Save import to V0.3.0

### ISSUE THREAD

**Issue by Scatlink** [vitor251093/KHMelonMix#153] opened 2024-06-09 22:48 UTC
**Describe the bug**
Copying your old .sav from V0.2.2 to continue playing the game in V0.3.0 does load, but doing any changes to any save file in-game (saving, deleting) doesn't persist when you close the emulator. Save data reverts to before you loaded.

**To Reproduce**
1. Go to 'Continue' to see your existing save files
3. Click on 'a save file' to load it
4. Scroll down to 'Save' and save into another save file for easy monitoring
5. Exiting to 'Title Screen' and checking your save files may show your save files as you left them, but the error shows when you close down then re-open the emulator to re-do Step 1 - your existing saves have reverted to before you clicked 'Save'.

**Expected behavior**
When you save or delete a file, it should stay like that when you re-open the emulator at a later point, not revert.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Melon Mix Version 0.3.0

**Additional context**
Steps for a roundabout way to bypass and fix this issue:
1. Open the emulator once
2. Open the emulator again for a separate instance
3. This will create a .ini.2 and a .sav.2, separate from the old imported .sav and current .ini
4. On the 2nd instance of the emulator; Go to 'Continue' to see your existing saves
5. On the 2nd instance of the emulator; Click on a 'save file' to load it
6. On the 2nd instance of the emulator; Scroll down to 'Save' and save into another save file for easy monitoring
7. On the 2nd instance of the emulator; Exiting to 'Title Screen' and check your save files may show your save files as you left them. If you were to close down the 2nd instance of the Emulator then re-open it, your existing saves will have stayed as they should!
8. Close down both instances of the emulator
9. Delete .ini.2 and .sav
10. Rename .sav.2 to .sav
11. Go to 'Continue' to see your existing save files
12. Click on 'a save file' to load it
13. Scroll down to 'Save' and save into another save file for easy monitoring
14. Exiting to 'Title Screen' and checking your save files may show your save files as you left them. If you were to now close the emulator and re-open it, your existing saves will still have stayed as they should, retroactively fixing the problem!

**Comment by vitor251093** [comment] 2024-06-10 22:01
I suppose that, for some reason, it's failing to overwrite the old save, but for some reason it isn't showing an error. I will test this possibility. Could you please attach the 0.2.2 save file?

**Comment by Scatlink** [comment] 2024-06-10 23:27
Good thing it was still sitting in my Recycle Bin; here it is

**Comment by vitor251093** [comment] 2024-06-10 23:30
@Scatlink I think it wasn't attached for some reason. At least I can't see it

**Comment by Scatlink** [comment] 2024-06-10 23:33
That's weird. I've DMd it directly to you via Discord

**Comment by vitor251093** [comment] 2024-06-19 13:44
I think the issue may be related to this fix:

https://github.com/melonDS-emu/melonDS/pull/1997

May be fixed if I use this one instead:

https://github.com/melonDS-emu/melonDS/pull/2058

**Comment by vitor251093** [comment] 2024-06-25 02:36
Nevermind, the condition in the other PR results in the same thing

**Comment by vitor251093** [comment] 2024-06-29 02:54
Quoting what fixed the issue for Scatlink:

> Also, I figured out what was causing my Save Data to not update when saving or deleting; when I download the new version I change the folder name. When I copy the game.nds and game.sav over, the .sav is still reading from the old version as the folder isn't the same, forcing me to delete the .ini and set everything up again, then open a second instance to make a .sav2. Then I have to rename that to .sav and it works.

> So going forward, I'll just update the existing folder and back up my current version elsewhere to overwrite if I want to clock back.

Since I couldn't manage to reproduce the issue (which seems to indicate it's the result of a system issue, a faulty config or a permission issue), and there is a workaround, I will close this issue for now.

If other people report the same issue, we will reopen this issue to investigate further.

I've also added a log to the only point in the code where I assume the issue can be detected. This may give us more insight in the future.

**Closed by vitor251093** 2024-06-29 02:54 UTC
Labels: bug
